try {
    eval("alert('ES6 Exception Handling)");
} catch(e){
    console.log("Error : " + e.name)
}